### ISSUE TITLE
Results not included in .rds

### ISSUE THREAD

**Issue by sarahcd** [movestore/SegmentData-bySpeed#2]
I ran the module and it appears to succeed, but when I go to "Show Downloads" and download the .rds file, it doesn't appear to include any segmentation results. I opened it in R Studio and viewed the summary, but it just appears to contain a MoveStack with the original attributes. Also I don't see any individual_local_identifier.

**Comment by andreakoelzsch** [comment]
long been fixed, individual_local_identifier has to come from Movebank App
