### ISSUE TITLE
reference to units

### ISSUE THREAD

**Issue by sarahcd** [movestore/SegmentData-bySpeed#5]
For this app, do the units matter, so long as they are consistent throughout the dataset? Data stored in 'ground-speed' in Movebank is defined as m/s, but data in cloud storage could come from elsewhere and speed units are reported in lots of ways, and you can't reliably guess by looking at the values. If the user enters the threshold value in m/s but stored them in other units, I suspect the app won't perform as described.

If yes, we should emphasize in the readme and settings that speed must be in m/s as stored in 'ground-speed' in Movebank. We should also add the units in the speed_artefakt.pdf.

If no, we should update the settings to say the threshold speed should be in the units of the data, and note that 'ground-speed' from Movebank will be in m/s.

**Comment by andreakoelzsch** [comment]
Thanks for the details, Sarah. This is not simple, unfortunately.

If the ground speed option is selected and all locations do have a ground speed measurement, then indeed m/s is not necessary and threshold and data unit must simply coincide. However, if some locations are missing an entry for ground speed, for those an estimated speed between locations is calulated in m/s. Then, the units would not fit together any more. The same is true if 
between-location speed is selected as option, then speed between locations is calculated in m/s.

So, I will adapt the readme to emphasize that ground speed must be in m/s as in Movebank. I will see how I can include that in the pdf. What do you think?

**Comment by annescharf** [comment]
@sarahcd @andreakoelzsch  in `move2` all attributes downloaded from movebank will have units assigned (using the r library `units`). I think we should start using this package in all apps, so units are with the data  an no assumptions are needed. For data uploaded through the cloud, I thought of making an app where units can be assigned to the attributes uploaded.

**Comment by sarahcd** [comment]
Those sound like good solutions. For cloud uploads, we should some how indicate the "Movebank" units for people using data from there, since unless they imported the data files themselves (this is where the user must see the expected units and confirm or convert to align values), probably a lot of people are not aware that units are assigned.

**Comment by annescharf** [comment]
in move2, if movebank data downloaded from the webpage are used to create a move2 object, units are also assigned. I was more thinking about people using data from elsewhere, to give them the option to assign units to their data.

**Comment by sarahcd** [comment]
ok! I wasn't sure if you would be able to a file originating as a download from the website.

**Comment by andreakoelzsch** [comment]
Hi both @annescharf and @sarahcd . I will update the App now on www as is. The units are taken care of, but might still be problematic if somebody loads a file form local. Lets be aware of it for support, it is described in details in the readme.
